version: '3.5'
services:
  php:
    build: .
    container_name: 'php'
    restart: "no"
    ports:
      - 8000:80
    environment:
      - APP_KEY="base64:tgEShQo7EjObwm8QaEyn/mpqMngpmIIJediWogs3AdM="
      - APACHE_RUN_USER=www-data
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
  mysql:
    image: mysql
    container_name: 'mysql'
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  adminer:
    image: adminer
    container_name: 'adminer'
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:mysql
  redis:
    image: redis:7.0-rc2-alpine
    container_name: 'redis'
    hostname: 'redis'
    ports:
      - ${REDIS_PORTS}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server -requirepass ${REDIS_PASSWORD} --include /usr/local/etc/redis/redis.conf
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: 'rabbitmq'
    ports:
        - ${RABBITMQ_PORTS1}
        - ${RABBITMQ_PORTS2}
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
        -   ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
